[project]
name = "2026sp-420-genericteamname"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fpdf2>=2.8.0",
    "pyqt6>=6.10.2",
    "openai>=1.0.0",
    "course-constraint-scheduler @ git+https://github.com/mucsci/Scheduler@5d904d0156cce60cd8ea4c333f26229019119487",
    "coverage>=7.13.5",
    "pytest-cov>=7.1.0",
    "qtbot>=0.0.1",
    "mocker>=1.1.1",
]
[tool.coverage.run]
source = ["./"]
omit = ["tests/*"]

[tool.pytest.ini_options]
addopts = "--cov --cov-report=xml --import-mode=importlib"
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest-mock>=3.15.1",
    "pytest-qt>=4.5.0",
]
